### PR TITLE
fixed #432 Build broken with JDK 21

### LINKED ISSUE #432: Build broken with JDK 21
I have pulled main and one test does not compile:

image

Error:
```
reference to exists is ambiguous
  both method exists(Path,LinkOption...) in FileSystemProvider and method exists(S3AsyncClient,S3Path) in S3FileSystemProvider match
```

I will provide a PR

### PR DESCRIPTION
**Pull request by stefanofornari**
*Issue #, if available:*
#432 

*Description of changes:*
fix for #432 Build broken with JDK 21

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by stefanofornari** [comment]
Sorry, as usual, I deleted the branch before PR is merged...

**Review by markjschreiber — CHANGES_REQUESTED** [review]
Can you try using the `S3AsyncClient` directly rather than casting it?

**Comment by markjschreiber** [comment]
I can see why there is an ambiguity but it's weird this only shows up in Java21. I have re-opened the PR for you and added a comment on it.

**Comment by stefanofornari** [comment]
I should have done...

**Comment by markjschreiber** [comment]
fixes #432

**Pull request merged**
