### PR TITLE
Fixing issues #115 and #161

### PR DESCRIPTION
**Pull request by stefanofornari**
*Issue #, if available:*
This PR covers issue #115 and #161 

S3 compatible services like minio do not like AWS S3 virtual-style addressing, where the bucket name is considered part of the hostname (e.g. pippo -> pippo.s3.eu-central-1.amazonaws.com).
We therefore set the path-style addressing by default for s3x provider, while we also give the possibility to configure it via the s3.spi.force-path-style.

I took this opportunity to make some improvements to the readme about the different configuration parameters. Please have a look and let me know if you like it. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by markjschreiber** [comment]
@stefanofornari there is a version conflict in this PR. This may be due to the order in which I merged your other PR? Can you resolve the conflict and then we can get these changes into the next release.

**Comment by stefanofornari** [comment]
> @stefanofornari there is a version conflict in this PR. This may be due to the order in which I merged your other PR? Can you resolve the conflict and then we can get these changes into the next release.

I should have done

**Review by markjschreiber — COMMENTED** [review]
I like this PR but I am wondering if there is a way to only force path style for `S3x` URIs? Path style requests are being retired from S3. Could the default be to not force path style but to allow that to be configured?

https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access

**Review by markjschreiber — APPROVED** [review]
Please ignore my last comment. I missed that force path style isn't actually the default.

**Pull request merged**
